# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.name = 'InconsistencyInspector' 
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
     
     # Disable USB Controller    
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
   

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     
     # Installation of Open JDK 7.
     sudo apt-get install -y openjdk-7-jdk
     
     # Installation of Mercurial.
     sudo apt-get -y install mercurial
     
     cd /home/vagrant/Desktop
     
     # Clone the project repo on desktop.
     hg clone https://bitbucket.org/rtholmes/inconsistencyinspectorresources
     sudo chmod 777 inconsistencyinspectorresources

    #Download project zip file
    sudo wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2011-InconsistencyInspector/archive/master.zip
        #Unzip the directory.
        unzip master.zip
        
        #Rename the directory
        sudo mv /home/vagrant/Desktop/ICSE-2011-InconsistencyInspector-master/ /home/vagrant/Desktop/II
                
        #Copy the content onto Desktop
        sudo cp -a II/build-vm/VM-Documents/installation.txt /home/vagrant/Desktop/
        sudo chmod 777 installation.txt
        
        sudo cp -a II/build-vm/VM-Documents/license.txt /home/vagrant/Desktop/
        sudo chmod 777 license.txt
        
        sudo cp -a II/build-vm/VM-Documents/readme.txt /home/vagrant/Desktop/
        sudo chmod 777 readme.txt
        
        sudo cp -a II/build-vm/VM-Documents/"How to use Inconsistency Inspector.desktop" /home/vagrant/Desktop/
        sudo chmod 777 "How to use Inconsistency Inspector.desktop"
        
        #Enable autologin.
		sudo mkdir /etc/lightdm/lightdm.conf.d
		chmod 777 /etc/lightdm/lightdm.conf.d
		cd /etc/lightdm/lightdm.conf.d/
		sudo touch 50-myconfig.conf
		echo -ne "[SeatDefaults]\nautologin-user=vagrant" >> 50-myconfig.conf
        
        # Open terminal on start up and disable lock.
        cd /home/vagrant/.config
		mkdir autostart	
		chmod 777 autostart
		sudo mv /home/vagrant/Desktop/II/build-vm/VM-Documents/gnome-terminal.desktop /home/vagrant/.config/autostart/
		sudo mv /home/vagrant/Desktop/II/build-vm/VM-Documents/disable-lock.desktop /home/vagrant/.config/autostart/
        
        # Remove unnecessary files.
        cd /home/vagrant/Desktop
        sudo rm -rf II/
        sudo rm -rf master.zip
        
        #Remove unnecessary sidebar icons.
		sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
		sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
		sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
		sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
		sudo rm -f "/usr/share/applications/ubuntuone-installer.desktop"
		sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
        
        # Reboot the machine.
		sudo reboot

  SHELL
end
